### ISSUE TITLE
"Cannot set property 'math' of undefined" attempting to load math.js

### ISSUE THREAD

**Issue by postmaxin** [josdejong/mathjs#1253]
When I attempt to load math.js inside a module of a module, I am getting what appears to be a Webpack error. Latest math.js, Chrome Version 69.0.3497.92 (Official Build) (64-bit)

Here is the error:

```
math.js:36 Uncaught TypeError: Cannot set property 'math' of undefined
    at webpackUniversalModuleDefinition (math.js:36)
    at math.js:37
webpackUniversalModuleDefinition @ math.js:36
(anonymous) @ math.js:37
```

In my index.html:

```
[...]

   <script type="module">
      import "./jquery-3.3.1.min.js";
      import { setupTable, calculateMeasurements } from "./renderer.js";
      $(document).ready(setupTable);
    </script>

[...]
```

Then, in renderer.js:

```
import './jquery-3.3.1.min.js';
import { WidthMeasurer, MeasurerUtil } from './measurer.js';

function cls() {
  $("#debug").empty();
}

[...]
```

... then, in measurer.js:

```
import * as math from './math.js';

class MeasurerError extends Error {}
class MeasurementOutOfBoundsError extends MeasurerError {}

export class MeasurerUtil {
[...]
```

Is webpack doing something strange, or am I doing something strange?

**Comment by josdejong** [comment]
Shouldn't

```js
import * as math from './math.js';
```
be
```js
import * as math from 'mathjs';
```
?

**Comment by postmaxin** [comment]
I have math.js in the same directory as my code. Trying to do it your way results in:

```
Uncaught TypeError: Failed to resolve module specifier "mathjs". Relative references must start with either "/", "./", or "../".
```

**Comment by josdejong** [comment]
Ah, so you use the bundled version. Maybe Webpack has issues bundling a bundled version or something? I don't really have a clue. Can you try to reproduce this issue in a minimal example?

**Comment by postmaxin** [comment]
Done:

```
<html>
  <head>
    <script type="module">
      import * as math from './math.js';
    </script>
  </head>
  <body>
    This will fail.
  </body>
</html>
```

Stick that and math.js in a directory. Serve that directory on the web (I used `php -Slocalhost:4444` in the directory). Navigate there in Chrome. Open JavaScript console. See this error:

```
Uncaught TypeError: Cannot set property 'math' of undefined
    at webpackUniversalModuleDefinition (math.js:36)
    at math.js:37
```

**Comment by Demonstrandum** [comment]
I get the same error, but I'm just trying to load the mathjs module through CDNJS. I've tried two ways:
```js
import * as math from 'https://cdnjs.cloudflare.com/ajax/libs/mathjs/5.4.1/math.js';
```
and
```js
import math from 'https://cdnjs.cloudflare.com/ajax/libs/mathjs/5.4.1/math.js';
```

Would be great if this could be made possible, even if it means adding another dist file entierly to the CDN.

**Comment by josdejong** [comment]
I expect this issue to be resolved in `mathjs@6.0.0`, which has ES6 modules. Will close this issue now. If there are still issues please open a new topic.

**Comment by Quoteme** [comment]
The error still has not been fixed:
```javascript
import math from 'https://unpkg.com/mathjs@6.2.3/dist/math.js';
```
results in:
```
Uncaught SyntaxError: The requested module 'https://unpkg.com/mathjs@6.2.3/dist/math.js' does not provide an export named 'default'
```

and 
```javascript
import * as math from 'https://unpkg.com/mathjs@6.2.3/dist/math.js';
```
results in:
```
Uncaught TypeError: Cannot set property 'math' of undefined
    at webpackUniversalModuleDefinition (math.js:36)
    at math.js:37
```

**Comment by josdejong** [comment]
@Quoteme thanks for reporting. 

The entry point for ES Modules is `main/esm/index.js`. The `module` field in `package.json` is pointing to this file, and bundlers like Webpack pick this up automatically. This entry point though will load hundreds of files though, since it's the unbundled source files, and I don't think unpkg.com likes that.

It would be nice if there is a way to make the bundle also work with `import`, maybe there is a way to actually get the bundled version working too.

**Comment by TCB13** [comment]
> It would be nice if there is a way to make the bundle also work with `import`, maybe there is a way to actually get the bundled version working too.

Yes :)

**Comment by josdejong** [comment]
Yes this is still the case because of the imports of npm dependencies which are used like `import { Decimal } from 'decimal.js'`.

**Comment by TCB13** [comment]
> Yes this is still the case because of the imports of npm dependencies which are used like `import { Decimal } from 'decimal.js'`.

Yes and that should work fine on a modern browser: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import

I actually tried to import `src/index.js` and it imported some files but there are a couple not working.
