### ISSUE TITLE
null/undefined treated as valid only for left side of comparison operators

### ISSUE THREAD

**Issue by rcrogers** [josdejong/mathjs#1391]
When the null value is on the right side, the correct error is thrown:
```
> require('mathjs').eval('1 > null')
TypeError: Unexpected type of argument in function larger (expected: number or Array or DenseMatrix or SparseMatrix or string or boolean or Matrix or BigNumber or Complex or Fraction, actual: null, index: 1)
```

However, when the null value is on the left side, the error mistakenly identifies the right side as the source of the problem:
```
> require('mathjs').eval('null > 1')
TypeError: Unexpected type of argument in function larger (expected: Array or DenseMatrix or SparseMatrix or Matrix, actual: number, index: 1)
```

**Comment by josdejong** [comment]
Thanks for reporting, the second error isn't very helpful indeed. 

It's not a very easy fix, has to do with the way the types of a function are matched against the different signatures of the function.

**Comment by rcrogers** [comment]
Makes sense.  Is it feasible to change the function def resolution so that a match only occurs if both operator arguments are compatible with the parameters of the function signature?

**Comment by josdejong** [comment]
The reason in this case is because there are signatures like `larger(any, DenseMatrix)` to allow multiplying a scalar and a matrix:

https://github.com/josdejong/mathjs/blob/develop/src/function/relational/larger.js#L108-L132

So, thinking about it, the solution may be quite easy (though it requires some labor and maintenance): replace the `any` wildcard with explicit types, ie. replace

```js
  const larger = typed('larger', {
    // ...
    'any, DenseMatrix': function (x, y) {
      return algorithm14(y, x, larger, true)
    },
    // ...
  })
```
with
```js
  const larger = typed('larger', {
    // ...
    'boolean | number | BigNumber | Fraction | Complex | Unit, DenseMatrix': function (x, y) {
      return algorithm14(y, x, larger, true)
    },
    // ...
  })
```
for all six occurrences, and do this for all operators (not only `larger`).

Downside is that when you add support for a new data type, you have to add the data type at many places. This can be partly resolved by defining one string on top and use that everywhere like:
```js
  const any = 'boolean | number | BigNumber | Fraction | Complex | Unit'

  const larger = typed('larger', {
    // ...
    `${any}, DenseMatrix`: function (x, y) {
      return algorithm14(y, x, larger, true)
    },
    // ...
  })
```

Anyone interested in thinking such a solution through and implementing the fix?

**Comment by nelsongnanaraj** [comment]
I too facing the same issue when I passed the null into the expression..

Please find the error message below
**ERROR TypeError: Unexpected type of argument in function addScalar (expected: number or string or boolean or BigNumber or Complex or Fraction, actual: null, index: 1)**

Do you have any workaround or temporary solution for this case ?

**Comment by m93a** [comment]
Hey Nelson,
The obvious workaround is *not passing null into expressions* 😅️ Is there a specific reason for why you do it?

**Comment by nelsongnanaraj** [comment]
I am working for dynamic expression parser using mathjs. So i have to allow the null values in mathjs. Here i shared the simple case of expression. 

`ifCondition(isNull(dateField1),today(),addDate(dateField1,add(numberField1,numberField2),'DAY'))`

**ifCondition**, **isNull**, **today**, **addDate** are my own defined functions. 

**IsNull** function is highly required for check most of the business cases. Without allowing null in data, How we can identify and return whether the specific expression having null or not.

**Comment by gwhitney** [comment]
This is definitely a bug, and it definitely still exists. In fact, it's worse, in that if M is a matrix, `null > M` **also** reports
`TypeError: Unexpected type of argument in function larger (expected: Array or DenseMatrix or SparseMatrix or Matrix, actual: number, index: 1)` when there isn't even any number in that expression... Hopefully this issue will go away in v13, but if it doesn't, it should be explicitly addressed.

**Comment by dpnova** [comment]
FWIW we encountered this when trying to use a unitless Unit value in a `>` comparison.

We have calc data moving between pint in python and mathjs in js - the pint dimensionless value value serialized as a mathjs Unit without a unit.

I think you'd normally expect to see an error about a comparison between a unit and non-unit value if you did something like `foo > 1` where foo is a unitless Unit - but instead we saw errors that brought us to this GH issue.

no fixes suggested from me, just adding a bit more signal

EDIT: sorry when i say we encountered, I mean the error message was surprising (we weren't using null, but I think the type matching issue is similar)

**Comment by josdejong** [comment]
Thanks for sharing your case David.

We still need help to work out a solution for this issue. Anyone?

**Comment by dpnova** [comment]
just for my understanding (relative newcomer) is this something to do with how typed functions are being used, not typedfunctions themselves? (as in the lib)

In our case the "fix" at our end is to have the python lib serializing the python values to mathjs compatible json simply turn a unitless pint value into a js literal number.

The reason I post this is because of the comment from @cshaa - where it would seem the two cases presented here may also involve an issue where mathjs isn't being used correctly/as expect.

**Comment by josdejong** [comment]
> just for my understanding (relative newcomer) is this something to do with how typed functions are being used, not typedfunctions themselves? (as in the lib)

This is not an issue with the `typed-function` library, but just how these functions are defined in `mathjs`.
