### ISSUE TITLE
Parenthesis in toString() method missing

### ISSUE THREAD

**Issue by sfdeveloperhub** [josdejong/mathjs#407]
Newbie to mathjs library and i was exploring the documentation to understand the library better. 

I created a JS Fiddle with the code straight from documentation http://jsfiddle.net/prakashfiddle/4y9441b7/2/ . As you can see, the output is without parentheses, although it should be.

**Comment by FSMaxB** [comment]
```sh
var node = math.parse('x^2 + 5*x');
var transformed = node.transform(function (node, path, parent) {
  if (node.type == 'SymbolNode' && node.name == 'x') {
    return new math.expression.node.ConstantNode(3);
  }
  else {
    return node;
  }
});
console.log(transformed.toString());
```

If I run this with the latest version (1.7.1) I get `3 ^ 2 + 5 * 3` which is correct.

The string get's parsed to a node tree like `(3^2) + (5 * x)` which, after transforming is `(3^2) + (5 * 3)`. Because the precedence of both `^` and `*` are higher than the precedence `+`, no parentheses are used so `toString` returns `3 ^ 2 + 5 * 3´.

**Comment by FSMaxB** [comment]
This is fixed in the development branch of version 1 for now. Maybe all of the examples should be checked before merging this into master. I don't know if I'll find the time to check every example in the documentation.

@josdejong: What do you think? Can documentation issues like this be commited to master without making a new release (1.7.2)? Also we probably should check all of the examples in v2 because the output for v2 is different.

**Comment by FSMaxB** [comment]
@sfdeveloperhub Thanks for pointing this out!

**Comment by sfdeveloperhub** [comment]
Sure, thanks for working on it. So is the future plan that toString() adds parentheses when necessary ? However, going by your explanation, should there be a parentheses around the '&' operation, given that it has higher precedence over '|'.

```
var node = math.parse('x|2&x|4');
var transformed = node.transform(function (node, path, parent) {
  if (node.type == 'SymbolNode' && node.name == 'x') {
    return new math.expression.node.ConstantNode(3);
  }
  else {
    return node;
  }
});
console.log(transformed.toString());

```

I thought the toString() output of expression tree should be the following. Thoughts ?

```
3 | (2 & 3) | 4
```

**Comment by FSMaxB** [comment]
The bitwise and has higher precedence than bitwise or, that's why it doesn't get put into parentheses. See the list of operator precedence: http://mathjs.org/docs/expressions/syntax.html
I admit that this might be a bit confusing because the precedence of some of those operators are defined differently elsewhere or aren't obvious.

The node tree that this expression get's parsed into is actually like this: `((x | (2 & x)) | 4)`

Version 2 of mathjs will default to trying to use the same parenthesis as in the input string, but that behaviour can be changed to show parentheses around every node or only the necessary ones (as is the default in v1).

**Comment by josdejong** [comment]
@FSMaxB I think we can just fix this in the v1_develop branch and do a bugfix release for it, if we would do this in the master branch the docs on npm and the website are still not up to date. A release is not much work. I had a quick look at the examples in the docs and these look up to date.

**Comment by josdejong** [comment]
Not sure, is this still an issue?

**Comment by FSMaxB** [comment]
I don't think so. The documentation has been fixed if I remember correctly. But I don't know for sure if v1 has been fixed.
